name: Daily HR Picks

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Fetch data & compute picks
        id: picks
        run: |
          source venv/bin/activate
          DATE=$(date +%F)
          python -m src.data_fetcher $DATE
          OUTPUT=$(python -m src.predict $DATE 10)
          echo "HR_PICKS<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT"       >> $GITHUB_OUTPUT
          echo "EOF"           >> $GITHUB_OUTPUT

      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: |
            *Today's Top 10 HR Picks*  
            ```  
            ${{ steps.picks.outputs.HR_PICKS }}  
            ```

