name: Daily HR Picks

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Prediction Date (YYYY-MM-DD)'
        required: false
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch data & compute picks
        id: picks
        run: |
          DATE="${{ github.event.inputs.date || '' }}"
          if [ -z "$DATE" ]; then
            DATE=$(date +%F)
          fi
          python -m src.predict "$DATE" 10 > hr_output.txt || { echo "Prediction script failed!"; exit 1; }
          if [ ! -s hr_output.txt ]; then
            echo "HR_PICKS=" >> "$GITHUB_OUTPUT"
            echo "RUN_DATE=$DATE" >> "$GITHUB_OUTPUT"
            echo "hr_output.txt was not generated or is empty."
            exit 1
          fi
          {
            echo "HR_PICKS<<EOF"
            cat hr_output.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          echo "RUN_DATE=$DATE" >> "$GITHUB_OUTPUT"

      - name: Send HR Picks to Slack
        if: ${{ steps.picks.outputs.HR_PICKS != '' }}
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "⚾ Daily HR Picks for ${{ steps.picks.outputs.RUN_DATE }}! ⚾",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "⚾ Daily HR Picks for ${{ steps.picks.outputs.RUN_DATE }}! ⚾"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Here are the top predictions:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```\\n${{ steps.picks.outputs.HR_PICKS }}\\n```"
                  }
                }
              ]
            }

