name: Daily HR Picks

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Fetch data & compute picks
        id: picks
        run: |
          source venv/bin/activate
          DATE=$(date +%F)
          python -m src.data_fetcher $DATE
          HR_OUTPUT=$(python -m src.predict $DATE 10)
          echo "HR_PICKS<<EOF" >> $GITHUB_OUTPUT
          echo "$HR_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send HR Picks to Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-webhook-type: incoming-webhook
          slack-message: |
            ⚾ Daily HR Picks for ${{ github.event.inputs.date || 'Today' }}! ⚾
            Here are the top predictions:
            ${{ steps.picks.outputs.HR_PICKS }}
